### ISSUE TITLE
初始化返回1025，网页版也无法登录

### ISSUE THREAD

**Issue by baryon** [nodeWechat/wechat4u#192]
初始化返回1025，网页版也无法登录。
在网页版；用其他的账号可以登录

用Mac微信客户端，出错账号也可以登录

难道是被服务器屏蔽了？

```

登录用户头像Data URL： data:img/jpg;base64,/9j/4AAQSk 。。。。。。。。。。z//2Q==
  wechat checkLogin:  +6s 201
  wechat checkLogin:  +1s https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=AkxA8Zk-QZbvox87kBdf7A-W@qrticket_0&uuid=4Yw_kZ27ww==&lang=zh-CN&scan=1493421876
  core AssertionError: 1205 == 0
    at Object.equal (/node_modules/wechat4u/src/util/global.js:53:14)
    at /node_modules/wechat4u/src/core.js:168:16
    at process._tickCallback (internal/process/next_tick.js:109:7) +854ms
  wechat AssertionError: 1205 == 0
    at Object.equal (/node_modules/wechat4u/src/util/global.js:53:14)
    at /node_modules/wechat4u/src/core.js:168:16
    at process._tickCallback (internal/process/next_tick.js:109:7) +0ms
2017-04-29T08:24:39+0900 <warn> wxBot.js:81 (WxBot.<anonymous>) 错误： { AssertionError: 1205 == 0
    at Object.equal (/node_modules/wechat4u/src/util/global.js:53:14)
    at /node_modules/wechat4u/src/core.js:168:16
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'AssertionError',
  actual: 1205,
  expected: 0,
  operator: '==',
  message: '1205 == 0',
  generatedMessage: true,
  [stack]: 'AssertionError: 1205 == 0\n    at Object.equal (node_modules/wechat4u/src/util/global.js:53:14)\n    at /node_modules/wechat4u/src/core.js:168:16\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
  response: 
   { status: 200,
     statusText: 'OK',
     headers: 
      { connection: 'close',
        'content-type': 'text/plain',
        'content-length': '653' },
     config: 
      { adapter: 
         { [Function: httpAdapter]
           [length]: 1,
           [name]: 'httpAdapter',
           [prototype]: httpAdapter { [constructor]: [Circular] } },
        transformRequest: 
         { '0': 
            { [Function: transformRequest]
              [length]: 2,
              [name]: 'transformRequest',
              [prototype]: transformRequest { [constructor]: [Circular] } } },
        transformResponse: 
         { '0': 
            { [Function: transformResponse]
              [length]: 1,
              [name]: 'transformResponse',
              [prototype]: transformResponse { [constructor]: [Circular] } } },
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: 
         { [Function: validateStatus]
           [length]: 1,
           [name]: 'validateStatus',
           [prototype]: validateStatus { [constructor]: [Circular] } },
        headers: 
         { Accept: 'application/json, text/plain, */*',
           'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.119 Safari/537.36',
           connection: 'close',
           cookie: 'pgv_pvi=5503086360290743000; pgv_si=s7138879740439556000; wxuin=2801122376; wxsid=EaO4U/hhK5GxBYL5; wxloadtime=1493421879; mm_lang=zh-CN; webwx_data_ticket=gSeS6R8SPMKbrrguB8a5Zztc; webwxuvid=40e656db4efd544af70e8374d9d4ac3202b2c8bb04ae2094464a1bd349930932983389369ae249e075d82e72a137a6b1; webwx_auth_ticket=CIsBENDu79oOGoABiC6Q3hXIXfnbMsrJ8pz0nZUngW7w7Wg9h+HHQnpO1H8/aARKPAJNYWpwDy8AJmW+D4scUwh5VxNfHOlVrEzq+QVrR5Fy05xJwmfKTFHAiA0+uLC7BvJSoYySNSsibm9DPANN8hBnCkp1Cyk8Os/XV8m3PuSL2TpjuZbtb86iR6I=',
           'Content-Type': 'application/json;charset=utf-8',
           'Content-Length': 147 },
        Cookie: 
         { pgv_pvi: '5503086360290743000',
           pgv_si: 's7138879740439556000',
           wxuin: '2801122376',
           wxsid: 'EaO4U/hhK5GxBYL5',
           wxloadtime: '1493421879',
           mm_lang: 'zh-CN',
           webwx_data_ticket: 'gSeS6R8SPMKbrrguB8a5Zztc',
           webwxuvid: '40e656db4efd544af70e8374d9d4ac3202b2c8bb04ae2094464a1bd349930932983389369ae249e075d82e72a137a6b1',
           webwx_auth_ticket: 'CIsBENDu79oOGoABiC6Q3hXIXfnbMsrJ8pz0nZUngW7w7Wg9h+HHQnpO1H8/aARKPAJNYWpwDy8AJmW+D4scUwh5VxNfHOlVrEzq+QVrR5Fy05xJwmfKTFHAiA0+uLC7BvJSoYySNSsibm9DPANN8hBnCkp1Cyk8Os/XV8m3PuSL2TpjuZbtb86iR6I=' },
        httpAgent: false,
        httpsAgent: false,
        method: 'POST',
        url: 'https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxinit',
        params: 
         { pass_ticket: '4UaBEXWHhmKZl%2Bnm2EGDBS0M%2FVn8s6w4gqPeTs7ZIOJ8um3uqLw3MVX9OLJFwfVe',
           skey: '@crypt_a6c9c482_f0811eea9f36fc0c8d6b4651aaa784dd',
           r: 1226739724 },
        data: '{"BaseRequest":{"Uin":2801122376,"Sid":"EaO4U/hhK5GxBYL5","Skey":"@crypt_a6c9c482_f0811eea9f36fc0c8d6b4651aaa784dd","DeviceID":"e332940940350592"}}' },
     data: 
      { BaseResponse: { Ret: 1205, ErrMsg: '' },
        Count: 0,
        ContactList: [ [length]: 0 ],
        SyncKey: { Count: 0, List: [ [length]: 0 ] },
        User: 
         { Uin: 0,
           UserName: '',
           NickName: '',
           HeadImgUrl: '',
           RemarkName: '',
           PYInitial: '',
           PYQuanPin: '',
           RemarkPYInitial: '',
           RemarkPYQuanPin: '',
           HideInputBarFlag: 0,
           StarFriend: 0,
           Sex: 0,
           Signature: '',
           AppAccountFlag: 0,
           VerifyFlag: 0,
           ContactFlag: 0,
           WebWxPluginSwitch: 0,
           HeadImgFlag: 0,
           SnsFlag: 0 },
        ChatSet: '',
        SKey: '',
        ClientVersion: 0,
        SystemTime: 0,
        GrayScale: 0,
        InviteStartCount: 0,
        MPSubscribeMsgCount: 0,
        MPSubscribeMsgList: [ [length]: 0 ],
        ClickReportInterval: 0 } },
  tips: '微信初始化失败' }
  wechat 登出中... +2ms
2017-04-29T08:24:39+0900 <info> wxBot.js:126 (WxBot.<anonymous>) 登出成功
  wechat 启动中... +2ms
```

**Comment by baryon** [comment]
如果开了两个实例，用同一个账号扫码，就会出现这个错误，第二次登录不了。第一次不自动退出。估计是微信的问题

**Comment by baryon** [comment]
似乎同开了多个实例无关:s

**Comment by baryon** [comment]
web客户端在失败以后有下面的数据传递

`Request URL:https://web.wechat.com/cgi-bin/mmwebwx-bin/webwxstatreport?fun=new&lang=en_US`

```
{
  "BaseRequest": {
    "Uin": "2801122386",
    "Sid": "",
    "DeviceID": "e698098790265898"
  },
  "Count": 1,
  "List": [
    {
      "Type": 2,
      "Text": "{\"type\":\"[init-error]\",\"data\":{\"text\":\"程序初始化失败，点击确认刷新页面\",\"code\":1,\"cookie\":\"webwxuvid=40e656db4efd544af70e8374d9d4ac3202b2c8bb04ae2094464a1bd349930932f0be1197a1ef1a7f71ff8790048697a7; pgv_pvi=7262043136; pgv_si=s8688701440; wxuin=2801122376; wxloadtime=1493518971; webwx_auth_ticket=CIsBEPztu7wLGoAB8VIRJHnlUv9gVCHZLlZ3FZUngW7w7Wg9h+HHQnpO1H8/aARKPAJNYWpwDy8AJmW+D4scUwh5VxNfHOlVrEzq+T9PMzsOUW2MQ0+T3LA3RKtXleBGoZfY0aBA2tvBO5mlGGg2ZOJ0L3tewmEdg7wpmMm3PuSL2TpjuZbtb86iR6I=; mm_lang=en_US; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; login_frequency=1; last_wxuin=null\"}}"
    }
  ]
}
```

**Comment by spacelan** [comment]
微信给你小黑屋了，估计是有频繁登录或者发送信息，等一段时间就好了

**Comment by baryon** [comment]
you are right
