### ISSUE TITLE
不定期(Sync Check)同步超时导致掉线

### ISSUE THREAD

**Issue by zhou-xinghai** [nodeWechat/wechat4u#198]
Sync Check正常polling大概25s中返回，然后进行下一次polling。但是我遇到了几次该调用不返回，900s整后才返回socket hang up,然后下次的Polling 返回window.synccheck={retcode:"1101",selector:"0"}。然后就是掉线了。昨天出现多次这个情况，请帮忙分析。
![Uploading wechat.png…]()

**Comment by zhou-xinghai** [comment]
日志信息如下：
Thu, 04 May 2017 08:01:07 GMT wechat begin syncPolling
Thu, 04 May 2017 08:01:07 GMT core begin syncCheck.
Thu, 04 May 2017 08:01:32 GMT core syncCheck: 111 res.data is  window.synccheck={retcode:"0",selector:"0"}
Thu, 04 May 2017 08:01:32 GMT wechat begin syncPolling
Thu, 04 May 2017 08:01:32 GMT core begin syncCheck.
Thu, 04 May 2017 08:16:32 GMT core Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Thu, 04 May 2017 08:16:32 GMT wxbot Error: 同步失败
    at /home/ec2-user/zhou/wechat_versions/wechat4u_30001_v3/src/core.js:306:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
Thu, 04 May 2017 08:16:33 GMT wechat begin syncPolling
Thu, 04 May 2017 08:16:33 GMT core begin syncCheck.
Thu, 04 May 2017 08:16:33 GMT core syncCheck: 111 res.data is  window.synccheck={retcode:"1101",selector:"0"}

**Comment by spacelan** [comment]
嗯，昨天微信服务器不稳定，我知道的好多机器人都跪了，
而且在最新版里，我已经设置了60s的超时时间，不会等到900s，你更新一下试试
