### ISSUE TITLE
二维码显示后一直不扫码就会挂掉

### ISSUE THREAD

**Issue by repertory** [nodeWechat/wechat4u#204]
如果二维码出现后忘记扫码，等过个6分钟左右的样子就会出现异常
同时每次手机上退出微信也会出现异常

> 异常提示

```
{ AssertionError: 400 != 400
    at Object.notEqual (/var/www/html/wechat/node_modules/wechat4u/lib/util/global.js:79:24)
    at /var/www/html/wechat/node_modules/wechat4u/lib/core.js:112:24
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'AssertionError',
  actual: 400,
  expected: 400,
  operator: '!=',
  message: '400 != 400',
  generatedMessage: true,
  response: 
   { status: 200,
     statusText: 'OK',
     headers: 
      { connection: 'close',
        'content-type': 'text/javascript',
        'content-length': '16' },
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        Cookie: [Object],
        httpAgent: false,
        httpsAgent: false,
        method: 'GET',
        url: 'https://login.wx.qq.com/cgi-bin/mmwebwx-bin/login',
        params: [Object],
        data: undefined },
     data: 'window.code=400;' },
  tips: '获取手机确认登录信息失败'
```

```
{ AssertionError: '1101' == 0
    at Object.equal (/var/www/html/wechat/node_modules/wechat4u/lib/util/global.js:69:24)
    at /var/www/html/wechat/node_modules/wechat4u/lib/core.js:363:24
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'AssertionError',
  actual: '1101',
  expected: 0,
  operator: '==',
  message: '\'1101\' == 0',
  generatedMessage: true,
  response: 
   { status: 200,
     statusText: 'OK',
     headers: 
      { connection: 'close',
        'access-control-allow-origin': '*',
        'content-type': 'text/javascript',
        'content-length': '46' },
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        Cookie: [Object],
        httpAgent: false,
        httpsAgent: false,
        method: 'GET',
        url: 'https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck',
        params: [Object],
        data: undefined },
     data: 'window.synccheck={retcode:"1101",selector:"0"}' },
  tips: '同步失败' }
```

**Comment by spacelan** [comment]
恩 这是符合预期的
