### ISSUE TITLE
不维护了么，貌似很多连不上的问题基本上都是https的原因

### ISSUE THREAD

**Issue by chengle123** [nodeWechat/wechat4u#277]
```
错误： { Error: connect ETIMEDOUT 101.227.160.102:443
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '101.227.160.102',
    port: 443,
    config:
     { adapter: [Function: httpAdapter],
       transformRequest: { '0': [Function: transformRequest] },
       transformResponse: { '0': [Function: transformResponse] },
       timeout: 60000,
       xsrfCookieName: 'XSRF-TOKEN',
       xsrfHeaderName: 'X-XSRF-TOKEN',
       maxContentLength: -1,
       validateStatus: [Function: validateStatus],
       headers:
        { Accept: 'application/json, text/plain, */*',
          'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36',
          connection: 'close',
          cookie: ' },
       Cookie:
        { pgv_pvi: '',
          pgv_si: '',
          wxuin: '2166428882',
          wxsid: '',
          wxloadtime: '',
          mm_lang: 'zh-CN',
          webwx_data_ticket: '',
          webwxuvid: '',
          webwx_auth_ticket: '',
          wxpluginkey: '1534482122' },
       httpAgent: false,
       httpsAgent: false,
       method: 'GET',
       url: 'https://webpush.wx.qq.com/cgi-bin/mmwebwx-bin/synccheck',
       params:
        { r: 1534495325040,
          sid: '',
          uin: '',
          skey: '',
          deviceid: '',
          synckey: '' },
       data: undefined },
    response: undefined,
    tips: '同步失败' }
```

**Comment by Zen-w** [comment]
我还在正常用啊，连接超时可能是暂时的网络问题，不知道你那里解决了不

**Comment by spacelan** [comment]
目前还能正常使用
