### ISSUE TITLE
向微信发送消息失败

### ISSUE THREAD

**Issue by Wlee2011** [nodeWechat/wechat4u#323]
uncaughtException AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (C:\Users\Administrator\git_workspace\wechat-openai-qa-bot\node_modules\wechat4u\src\util\global.js:53:14)
    at C:\Users\Administrator\git_workspace\wechat-openai-qa-bot\node_modules\wechat4u\src\core.js:476:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (file:///C:/Users/Administrator/git_workspace/wechat-openai-qa-bot/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:770:5)
    at async WechatifiedUserClass.say (file:///C:/Users/Administrator/git_workspace/wechat-openai-qa-bot/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at async WechatyImpl.onReady (file:///C:/Users/Administrator/git_workspace/wechat-openai-qa-bot/src/bot.ts:382:3) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}

请问这是什么问题

注：
hook群里对方发送的消息是没问题的

**Comment by xrl12** [comment]
可以粘贴一下你sendMsg里面的username吗
