### ISSUE TITLE
状态同步超过“”N“s未响应，5s后尝试重启 ，时不时会出现这个，而且只有手动重启Docker

### ISSUE THREAD

**Issue by HarveyJiang** [nodeWechat/wechat4u#338]
![image](https://github.com/nodeWechat/wechat4u/assets/6862629/4389f449-291d-41b3-8dc5-e058289da297)
uncaughtException GError: 状态同步超过273.226s未响应，5s后尝试重启
    at Wechat.checkPolling (/wechaty/node_modules/wechat4u/lib/wechat.js:298:19)
    at Timeout._onTimeout (/wechaty/node_modules/wechat4u/lib/wechat.js:319:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: 状态同步超过273.226s未响应，5s后尝试重启\n' +
    '    at Wechat.checkPolling (/wechaty/node_modules/wechat4u/lib/wechat.js:298:19)\n' +
    '    at Timeout._onTimeout (/wechaty/node_modules/wechat4u/lib/wechat.js:319:25)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

有试用这个遇到这个情况么？之前看Issues有人提，没有看到解决方式，还是这个微信限制。

谢谢

**Comment by allforone** [comment]
有解决么

**Comment by HarveyJiang** [comment]
> 有解决么

没有，目前遇到这种情况，只有重启然后重新扫码登录。

**Comment by SHADOW-LI0327** [comment]
我这里各种尝试解决了下，可以试试
1. 通过Contact的Api搜索自己的微信给自己发消息，会报错，但是可以有效方式防止状态同步
2. 移动端扫码登录的设备不要关闭微信，让他一直和服务器通信

**Comment by ZohnnyCode** [comment]
有解决吗?

**Comment by SHADOW-LI0327** [comment]
> 有解决吗?
OK的，额外补充一下
1. 使用的账号尽量做点别的事情，比如打开小程序，发发朋友圈之类的
2. 设备尽量用安卓，苹果测试下来会断，安卓挂后台进程双开微信还方便监控

![image](https://github.com/user-attachments/assets/8b79c718-3423-4307-9c9c-d210e7ad57ab)
