### ISSUE TITLE
出现uncaughtException AssertionError [ERR_ASSERTION]: -1 == 0 是什么问题

### ISSUE THREAD

**Issue by eyunfeis** [nodeWechat/wechat4u#341]
运行代码出现以下错误信息是什么问题：
`uncaughtException AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (E:\dev\wechat\node_modules\wechat4u\lib\util\global.js:69:24)
    at E:\dev\wechat\node_modules\wechat4u\lib\core.js:326:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: -1 == 0\n' +
    '    at Object.equal (E:\\dev\\wechat\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at E:\\dev\\wechat\\node_modules\\wechat4u\\lib\\core.js:326:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)'
}`

**Comment by why-qw1ko** [comment]
解决了吗？我也一直报这个错误，但是机器人还是正常运行
