### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by cloudy-sfu** [nodeWechat/wechat4u#344]
After scanning the code and confirming the login on the WeChat mobile client, the QR code changes immediately (even if the QR code was generated less than 1 minute ago). The login fails, returning the following error.

This account was banned by the WeChat web version, but not by the PC version. I don’t know if this project simulates PC login.

```
[2024-07-06T09:05:09.590] [INFO] default - Wechat client start!
[2024-07-06T09:05:55.681] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:69:24)
    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:229:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:229:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
[2024-07-06T09:10:59.473] [ERROR] default - error: AssertionError [ERR_ASSERTION]: 400 != 400
    at Object.notEqual (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:79:24)
    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:139:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 400 != 400\n' +
    '    at Object.notEqual (/home/cld/wechat2tg/node_modules/wechat4u/lib/util/global.js:79:24)\n' +
    '    at /home/cld/wechat2tg/node_modules/wechat4u/lib/core.js:139:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

扫描登录二维码后出现错误。

扫码并在微信手机客户端确认登录后，本项目的二维码立即变更（即使二维码生成时间不足1分钟），且登录失败，返回以下错误。

本账号被微信网页版封禁，但没有被PC端封禁，不知道这个项目是否模拟了PC端登录。

**Comment by why-qw1ko** [comment]
解决了吗？我也是这个问题，但是报的是 -1 != 0，机器人还在正常运行
