### ISSUE TITLE
报这个错误

### ISSUE THREAD

**Issue by fanly** [nodeWechat/wechat4u#41]
wechat Error: connect ETIMEDOUT 101.226.76.164:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14) +9s
  wechat Error: connect ETIMEDOUT 101.226.76.164:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14) +9s
  wechat Error: 同步失败
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/wechat4u/lib/wechat.js:594:15
    at process._tickCallback (node.js:406:9) +0ms
  wxbot Error: 同步失败
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/wechat4u/lib/wechat.js:594:15
    at process._tickCallback (node.js:406:9) +1ms
  app 关闭注销连接 +487ms 0

**Comment by stonexer** [comment]
应该是网络问题吧，ETIMEDOUT 101.226.76.164:443

还存在么

**Comment by fanly** [comment]
会有很大的机率出现，扫码扫不上去的情况，怎么扫都进不去，或者扫进去了又失败了

**Comment by stonexer** [comment]
@spacelan 
最近是好像扫码会超时，大哥有遇到么

**Comment by spacelan** [comment]
最近没怎么玩儿，不过我很早之前就遇到过反复扫码失败的情况

**Comment by fanly** [comment]
有解决方案吗？

**Comment by spacelan** [comment]
现在应该好了
