### ISSUE TITLE
会报TypeError: Parameter 'url' must be a string, not undefined错误

### ISSUE THREAD

**Issue by fanly** [nodeWechat/wechat4u#45]
如题，会报TypeError: Parameter 'url' must be a string, not undefined错误。请问这么处理呢？经常性的

**Comment by stonexer** [comment]
可以定位下报错的函数么，我这儿没重现出来。

**Comment by fanly** [comment]
wechat 启动失败 +2ms [Error: 获取扫描状态信息失败]
  app 关闭登陆失败连接 +2ms 0
  wechat TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:73:11)
    at Object.urlParse [as parse] (url.js:67:5)
    at cookie.prepare (/Users/wuhaiping/git/learning/bamaso/bamasobot/node_modules/cookie-manager/index.js:95:19)
    at /Users/wuhaiping/git/learning/bamaso/bamasobot/lib/third/wechat4u/request.js:25:61
    at process._tickCallback (node.js:406:9) +2ms
  app 新连接 +2s 1
  wechat CheckScan +31ms
  wechat Error: 扫描状态code错误: 408
    at /Users/wuhaiping/git/learning/bamaso/bamasobot/lib/third/wechat4u/wechat.js:147:15
    at process._tickCallback (node.js:406:9) +27s
  wechat 启动失败 +0ms [Error: 获取扫描状态信息失败]
  app 关闭登陆失败连接 +1ms 0
  wechat TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:73:11)
    at Object.urlParse [as parse] (url.js:67:5)
    at cookie.prepare (/Users/wuhaiping/git/learning/bamaso/bamasobot/node_modules/cookie-manager/index.js:95:19)
    at /Users/wuhaiping/git/learning/bamaso/bamasobot/lib/third/wechat4u/request.js:25:61
    at process._tickCallback (node.js:406:9) +0ms
  app 新连接 +2s 1
  wechat CheckScan +22ms

**Comment by stonexer** [comment]
Fix this.

**Comment by fanly** [comment]
谢谢
