### ISSUE TITLE
挂个几个小时就会退出，怎么保持一直登录运行？

### ISSUE THREAD

**Issue by Flyphy** [nodeWechat/wechat4u#83]

**Comment by spacelan** [comment]
自己写服务跑的么？

**Comment by Flyphy** [comment]
没改动啥，放树莓派上跑。
vnc 登录树莓派，shell 信息如下
[http://ww1.sinaimg.cn/large/006tNc79gw1f9cnyq89f3j30lu0dyq84.jpg](url)

**Comment by Flyphy** [comment]
node版本v7.0.0
npm版本3.10.8

**Comment by spacelan** [comment]
这个偶尔几个503是正常的，直接导致退出的log有么

**Comment by Flyphy** [comment]
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Status Report +1ms
  wechat Sync Check Selector:  +497ms 2
  wechat Sync Check Selector:  +25s 0
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +252ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +3s 2
  wechat syncPolling messages count:  +297ms 1
又玩手机辣
  wechat batchGetContact data length:  +304ms 1
联系人数量： 7
  wechat Sync Check Selector:  +14ms 2
  wechat syncPolling messages count:  +315ms 1
又玩手机辣
  wechat batchGetContact data length:  +376ms 1
联系人数量： 7
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Status Report +1ms
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +468ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +1s 2
  wechat Sync Check Selector:  +26s 0
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +230ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +26s 0
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +220ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +27s 0
  wechat Sync Check Selector:  +25s 0
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +241ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +28s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Status Report +1ms
  wechat Sync Check Selector:  +375ms 2
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +490ms
错误： Error: 同步失败
    at /root/wechat4u/src/core.js:302:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +26s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +18s 2
  wechat syncPolling messages count:  +316ms 1
又玩手机辣
  wechat batchGetContact data length:  +260ms 1
联系人数量： 7
  wechat Sync Check Selector:  +533ms 2
  wechat syncPolling messages count:  +281ms 1
又玩手机辣
  wechat batchGetContact data length:  +312ms 1
联系人数量： 7
  wechat Sync Check Selector:  +287ms 2
  wechat syncPolling messages count:  +362ms 1
又玩手机辣
  core Error: Request failed with status code 503
    at createError (/root/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/wechat4u/node_modules/axios/lib/adapters/http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +289ms
  wechat Error: 批量获取联系人失败
    at /root/wechat4u/src/core.js:235:13
    at process._tickCallback (internal/process/next_tick.js:103:7) +2ms
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Sync Check Selector:  +25s 0
  wechat Status Report +1ms
  wechat Sync Check Selector:  +322ms 2
  wechat Sync Check Selector:  +26s 0

**Comment by spacelan** [comment]
这个log不是还能够正常同步么？

`wechat Sync Check Selector: +26s 0`表示同步成功但是没有新消息

**Comment by Flyphy** [comment]
有可能是树莓派休眠导致的问题

**Comment by Flyphy** [comment]
(node:4466) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'UserName' of undefined
(node:4466) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
