### ISSUE TITLE
  core Error: socket hang up 

### ISSUE THREAD

**Issue by Flyphy** [nodeWechat/wechat4u#86]
core Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +45s

这个 error会导致程序崩掉，是什么原因造成的

**Comment by spacelan** [comment]
还有更多的信息么，这样我看不出来

**Comment by Flyphy** [comment]
上下的 log 就是正常的wechat Sync Check Selector，中间有一些503同步失败的 log，树莓派试了很多次都是2-10个小时左右就登出了，树莓派 log也没有登出 log 打出，最后的 log 就是一些wechat Sync Check Selector。

这个对 node 版本有什么要求，树莓派上试了 node 7.0.0跟4.6.1都有这个问题。

我在阿里云上跑下看看能否复现。

**Comment by spacelan** [comment]
我在x86上能跑两三天吧。。

没打登出log应该是进程直接挂掉了

**Comment by marx828** [comment]
@Flyphy 请问这个问题解决了吗？
