### ISSUE TITLE
浏览器上传媒体文件失败！

### ISSUE THREAD

**Issue by udbmnm** [nodeWechat/wechat4u#94]
浏览器通过uploadMedia上传File对象总是失败，我看量请求根本还没发，不到是什么原因，还在查看中

**Comment by js571** [comment]
貌似不只浏览器，在纯node端中上传也失败，错误如下：

```
core Error: write after end
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:413:15)
    at Writable.RedirectableRequest._write (/Users/apple/Documents/git/C2C/wechat/wechat-emoticon/node_modules/wechat4u/node_modules/axios/node_modules/follow-redirects/index.js:153:23)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at Array.WritableState.onwrite (_stream_writable.js:89:5)
    at _stream_writable.js:383:15
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at TLSSocket.WritableState.onwrite (_stream_writable.js:89:5) +0ms
[Error: 上传媒体文件失败]
  core Error: Request failed with status code 404
    at createError (/Users/apple/Documents/git/C2C/wechat/wechat-emoticon/node_modules/wechat4u/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/Users/apple/Documents/git/C2C/wechat/wechat-emoticon/node_modules/wechat4u/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/apple/Documents/git/C2C/wechat/wechat-emoticon/node_modules/wechat4u/node_modules/axios/lib/adapters/http.js:186:11)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17) +2s


```

**Comment by udbmnm** [comment]
在浏览器是请求都没发，和node不一样的错误，我之前是准备浏览器做主动发送文件，不过浏览器权限根本做不到放弃了

**Comment by spacelan** [comment]
好像是微信API有变动，我有时间再看看

**Comment by udbmnm** [comment]
这个可以关闭下了

**Comment by udbmnm** [comment]
这个可以关闭下了
